const char *JSON_STATUS = "{"
                          "\"tin\": %f,"
                          "\"tout\": %f,"
                          "\"s0\": %d,"
                          "\"s1\": %d,"
                          "\"s2\": %d,"
                          "\"s3\": %d,"
                          "\"s4\": %d,"
                          "\"s5\": %d,"
                          "\"ax\": %d,"
                          "\"ay\": %d,"
                          "\"az\": %d,"
                          "\"gx\": %d,"
                          "\"gy\": %d,"
                          "\"gz\": %d,"
                          "\"dist\": %d,"
                          "\"left\": %d,"
                          "\"right\": %d,"
                          "\"lspeed\": %d,"
                          "\"rspeed\": %d"
                          "}";

const char *JSON_DISTANCE = "{\"dist\": %d}";